name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        webpack-version: [latest, next, webpack-3]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn, build, and test
      run: |
        yarn
        yarn install webpack@${WEBPACK_VERSION}
        yarn list webpack
        yarn test
      env:
        CI: true
        WEBPACK_VERSION: ${{ matrix.webpack-version }}